spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: coreapi-application-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB