name: Deploy UI Reader

on:
  push:
    branches:
      - main
    paths:
      - 'ui-reader/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./ui-reader
          push: true
          tags: hikmetcakirdev/uireader:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/hikmetcakir
            sed -i 's|hikmetcakirdev/uireader:.*|hikmetcakirdev/uireader:latest|' docker-compose.yml
            docker-compose pull uireader
            docker-compose up -d uireader