name: Deploy Config API

on:
  push:
    branches:
      - main
    paths:
      - 'config-api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./config-api
          push: true
          tags: hikmetcakirdev/configapi:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/hikmetcakir
            sed -i 's|hikmetcakirdev/configapi:.*|hikmetcakirdev/configapi:latest|' docker-compose.yml
            docker-compose pull configserver
            docker-compose up -d configserver